version: '3.8'

services:
  mailAttachmentPrinter:
    image: mailattachmentprinter:v1.1
    container_name: mailAttachmentPrinter
    restart: on-failure
    ## Uncomment the following two lines when using config file
    # volumes:
    #   - ./config:/app/config
    ## Uncomment volumes and the following line when usinf tide extension
    #   - ./tides:/app/tides
    ## Uncomment the following two lines when using environment file
    # env_file:
    #   - env
